services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    volumes:
      - ./frontend:/app
  strapi:
    build:
      context: ./backend
    container_name: strapi_app
    volumes:
      - ./backend:/data
    ports:
      - "1337:1337"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: strapi_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
  
